nielsfaber/scheduler-card

README.md

Note HACS installation is available

---

src/scheduler-card.ts

Change MDI to hass

---

src/default-config.ts

Add more domain icons

---

README.md

set brightness to 40 as suggested by name of action.

correct brightness value

---

src/default-config.ts

So it shows up with icons. (sorry for the wrong commit message)

Add icon for fan

---

src/localize/languages/no.json

Rough translation to Norwegian. The words "on" and "at" might depend on context, so it might not be perfect as it is now.

Added Norwegian translation

---

package.json
src/localize/languages/ru.json
src/localize/localize.ts

Translate to the Russian language.

add ru translate

---

.github/workflows/validate.yaml

Fix GitHub Actions

---

README.md
src/localize/languages/en.json

Rename every day to daily

---

src/standard-configuration.json

Add unit, add icons, and more services.

Improve services for humidifier

---

src/localize/languages/ro.json
src/localize/localize.ts

Added Romanian language

---

src/localize/languages/hu.json

It's possible that some words are wrongly agglutinated, I can only know this from the context where they appear. I will fix it after the next release.

Update hungarian translation

---

src/localize/languages/it.json

Italian translation - it.json

---

src/localize/languages/it.json

The placehorders have been translated in italian (like "alle {ora}") but i think they should be to be in english

Removed the italian translations of the placeholders

---

src/localize/languages/cs.json

"scheduler": "Plánovač",
"actions": {
"add": "přidat plán",
"cancel": "zrušit",
"next": "další",
"save": "uložit",
"delete": "smazat"
Line 4 is not translated, there was no change in add

New Czech update

---

src/localize/languages/cs.json

Minor translation correction cs.json

---

src/localize/languages/ro.json

Update RO translations

---

src/const.ts
src/custom-elements/condition-entity-row.ts
src/custom-elements/scheduler-card-editor.ts
src/custom-elements/scheduler-entities-card.ts
src/custom-elements/scheduler-entity-row.ts
src/custom-elements/scheduler-entitypicker-card.ts
src/custom-elements/scheduler-options-card.ts
src/custom-elements/scheduler-timepicker-card.ts
src/date-time.ts
src/entity.ts
src/formatAction.ts
src/scheduler-card.ts
src/standard-configuration/climate.ts
src/standard-configuration/group.ts
src/standard-configuration/standardActions.ts
src/types.ts

- update support for group entities
- add support for hiding entity name in overview page
- improve workday sensor support

Improvements

---

.gitignore

Add ds_store to gitignore

---

.github/workflows/fixed_in.yaml

This runs CI on comments and puts out a reminder comment.

Add fixed in CI

---

src/localize/languages/et.json

Quick (and maybe dirty)- will improve if needed :-)
Best, JR

et.json for 1.9.0

---

src/localize/languages/fr.json

Better fr phrases

---

src/custom-elements/timeslot-editor.ts

Hope this makes sense. With this change, we could be allowed to create hourly schedules for a whole day. E.g. I can run a pool pump every 3 hours for an hour from midnight.

feat: increment up to 24 entries in daily schedule

---

src/localize/languages/fr.json

Just updated a few of the entries 🥐 
One is hard, "covers" for which there isn't really one term in french but "couvertures" should at least be understandable (connecteurs, not so).
We do use weekend for the end of the week, there isn't any other word in use nowadays.
Changed a few other for a more proper translation in the context of this component.
Feel free to accept or not those suggestions

Update to the french translation for a more direct understanding.

---

src/localize/languages/fr.json

space is missing, must be outside condition
my bad, I should have checked better :(

Fix space in condition

---

README.md
src/localize/languages/fr.json

Hi, thanks for this great component! After an hour reading different issues, trying different things, I realised my problem, that seems the problem of many other people too due to the related issues:
- I was looking for an awesome scheduling card and I found the https://github.com/nielsfaber/scheduler-card
- I followed the instructions and successfully installed the card
- Was very excited to test it so I went to the HA panel, added a card and omg it worked! But then I saw the message: *scheduler/add Service not found*
- I've started reading different issues, at least 3 or 4. I've found that there was a different repo to open issues, but didn't understand why, I've thought maybe it's a dependency...
- More reading and I've discovered that I should have the integration ready, but was …

Update install docs

---

package.json

This fixes the build scripts so they work.

Fix build scripts

---

src/localize/languages/en.json

Fixes #242. It could also be "device groups".

Change "groups" to "entity groups"

---

README.md

Fix images

---

.github/workflows/check.py
.github/workflows/validate.yaml

Tries to load all languages, and checks for completeness. Also switches to the new HACS action.

Workflow improvements

---

src/localize/languages/pl.json

This is just Polish translation for set_cover_tilt_position action

Add set_cover_tilt_position translation to Polish

---

README.md

Fix typo in list of options config

---

src/localize/languages/no.json

Additional entries translated
Corrected typos

Update of norwegian translation

---

src/localize/languages/cn.json

Add translation for Chinese （简体中文）

Add translation for Chinese （简体中文）

---

src/components/variable-slider.ts

Per conversation with Niels. I've tested this locally, confirm that fractional changes are saved and persist across restarts of HA.

Fixing a bug in saving fractional values

---

src/localize/languages/pt-BR.json
src/localize/localize.ts

I corrected the names of the files and found that it was wrong, which made the translation not be applied and the card was in english.

Add filename fix! Portuguese Brazilian translation!

---

src/localize/languages/fr.json

Correct some french translations
Fix unclear translations for all/any, as it had the same meaning for both translations in french (still not perfect but I think it's the best we can get with one word)

Update french translations

---

src/components/variable-slider.ts

Hello, it's for fix issue with last version of Home Assistant 
Core 2023.11.1
Supervisor 2023.10.1
Operating System 11.1
Interface utilisateur 20231030.1

Update variable-slider.ts replace pin by labeled

---

package.json
rollup.config.js

Fix build dependencies

---

src/components/timeslot-editor.ts

Show icons in time slot editor when names are too long

---

src/localize/languages/de.json

`Added missing de (German) translations.`
The PullRequest does not need any further description 😄. 
Best regards
Denny

Added missing de (German) translations.

---

src/localize/languages/pl.json

First of all, thank you for your support and for working on V4.
I'm adding some fixes for V4 translations.
Before I move forward I'd like to ask about singular/plural form in domains: https://github.com/Misiu/scheduler-card/blob/v4/src/localize/languages/en.json#L62
for example, you have `locks` and `lawn mower`. Not sure which one is preferred.
I just noticed that there are changes in en.json that aren't added into pl.json, I'll try to add missing items.
Do you plan any additional changes into en.json for V4?
Do you have any suggestions on when V4 will be released? 😎

Update pl.json - partial translation

---

src/localize/languages/fr.json

[v4] Update fr.json

---

src/data/selectors/validate_selector_value.ts

Fixes issue with number condition were valid numbers are not detected and therefore not saved.
Fixes #959

#959 Conditions aren't being saved 

---

src/data/actions/compute_action_domains.ts
src/dialogs/dialog-select-action.ts

Auto select the domain and directly show the actions if there is only one domain configured

Domain autoselect
